// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://koxounvxtnsbcpbvobfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtveG91bnZ4dG5zYmNwYnZvYmZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDMzMDIsImV4cCI6MjA1OTU3OTMwMn0.9Jml05K_BAQ8GyVHko4inW6sAYUaiQ9GpNnUSwuZTug";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);